from __future__ import annotations

import json
import hashlib
import os
from pathlib import Path
import subprocess
from types import SimpleNamespace

import pytest

from release_packaging import release_identity as packaging
from release_packaging.release_identity import (
    RELEASE_IDENTITY_BINDING_MODULE,
    RELEASE_IDENTITY_FILENAME,
    ReleaseIdentityPackagingError,
    prepare_frozen_release_identity,
)


def _run(*arguments: str, cwd: Path) -> str:
    completed = subprocess.run(
        list(arguments),
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return completed.stdout.strip()


def _repository(tmp_path: Path, *, version: str = "1.1.0") -> Path:
    root = tmp_path / "repository"
    (root / "backend").mkdir(parents=True)
    (root / "package.json").write_text(
        json.dumps({"name": "suxiaoyou", "version": version}) + "\n",
        encoding="utf-8",
    )
    (root / "backend" / "pyproject.toml").write_text(
        f'[project]\nname = "suxiaoyou"\nversion = "{version}"\n',
        encoding="utf-8",
    )
    (root / "tracked.txt").write_text("release input\n", encoding="utf-8")
    _run("git", "init", "--quiet", cwd=root)
    _run("git", "config", "user.email", "release@example.invalid", cwd=root)
    _run("git", "config", "user.name", "Release Test", cwd=root)
    _run("git", "add", ".", cwd=root)
    _run("git", "commit", "--quiet", "-m", "fixture", cwd=root)
    return root


def test_generates_canonical_resource_and_spec_inputs(tmp_path: Path) -> None:
    repository = _repository(tmp_path)
    work_root = tmp_path / "absolute-work"
    expected_commit = _run("git", "rev-parse", "HEAD^{commit}", cwd=repository)

    result = prepare_frozen_release_identity(
        repository_root=repository,
        work_root=work_root,
    )

    assert result.app_version == "1.1.0"
    assert result.identity is not None
    assert result.identity.app_version == "1.1.0"
    assert result.identity.release_commit == expected_commit
    assert result.source_path == work_root / RELEASE_IDENTITY_FILENAME
    assert result.binding_module_path == (
        work_root / f"{RELEASE_IDENTITY_BINDING_MODULE}.py"
    )
    assert result.binding_module_root == work_root
    assert result.hiddenimports == (RELEASE_IDENTITY_BINDING_MODULE,)
    assert result.datas == ((str(result.source_path), os.path.join("app", "data")),)
    assert result.source_path.read_bytes() == (
        b'{"app_version":"1.1.0","release_commit":"'
        + expected_commit.encode("ascii")
        + b'","schema_version":1}\n'
    )
    assert result.source_path.stat().st_mode & 0o777 == 0o600
    expected_digest = hashlib.sha256(result.source_path.read_bytes()).hexdigest()
    assert result.binding_module_path.read_text(encoding="ascii") == (
        "# Generated by release_packaging.release_identity; do not edit.\n"
        f'RELEASE_IDENTITY_SHA256 = "{expected_digest}"\n'
    )
    assert result.binding_module_path.stat().st_mode & 0o777 == 0o600


def test_legacy_version_checks_consistency_but_emits_no_resource(tmp_path: Path) -> None:
    repository = _repository(tmp_path, version="1.0.9")
    work_root = tmp_path / "not-created"

    result = prepare_frozen_release_identity(
        repository_root=repository,
        work_root=work_root,
    )

    assert result.app_version == "1.0.9"
    assert result.identity is None
    assert result.source_path is None
    assert result.binding_module_path is None
    assert result.binding_module_root is None
    assert result.hiddenimports == ()
    assert result.datas == ()
    assert not work_root.exists()

    (repository / "backend" / "pyproject.toml").write_text(
        '[project]\nname = "suxiaoyou"\nversion = "1.0.8"\n',
        encoding="utf-8",
    )
    with pytest.raises(ReleaseIdentityPackagingError, match="do not match"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=work_root,
        )


def test_dirty_tracked_checkout_is_rejected_and_untracked_is_ignored(
    tmp_path: Path,
) -> None:
    repository = _repository(tmp_path)
    (repository / "untracked-build-output").write_text("ignored\n", encoding="utf-8")

    accepted = prepare_frozen_release_identity(
        repository_root=repository,
        work_root=tmp_path / "clean-work",
    )
    assert accepted.identity is not None

    (repository / "tracked.txt").write_text("tampered\n", encoding="utf-8")
    with pytest.raises(ReleaseIdentityPackagingError, match="checkout is dirty"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "dirty-work",
        )
    assert not (tmp_path / "dirty-work" / RELEASE_IDENTITY_FILENAME).exists()


def test_assume_unchanged_and_skip_worktree_cannot_hide_tracked_changes(
    tmp_path: Path,
) -> None:
    repository = _repository(tmp_path)
    _run("git", "update-index", "--assume-unchanged", "tracked.txt", cwd=repository)
    (repository / "tracked.txt").write_text("hidden tamper\n", encoding="utf-8")

    with pytest.raises(ReleaseIdentityPackagingError, match="unsafe index flags"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "assume-unchanged-work",
        )


def test_duplicate_package_keys_and_noncanonical_versions_are_rejected(
    tmp_path: Path,
) -> None:
    repository = _repository(tmp_path)
    (repository / "package.json").write_text(
        '{"version":"1.1.0","version":"1.1.0"}\n',
        encoding="utf-8",
    )
    with pytest.raises(ReleaseIdentityPackagingError, match="strict UTF-8 JSON"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "work-duplicate",
        )

    (repository / "package.json").write_text(
        '{"version":"01.1.0"}\n', encoding="utf-8"
    )
    with pytest.raises(ReleaseIdentityPackagingError, match="not X.Y.Z"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "work-version",
        )


def test_noncanonical_git_commit_is_rejected(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    repository = _repository(tmp_path)
    monkeypatch.setattr(packaging, "_git_commit", lambda _repository: "0" * 40)

    with pytest.raises(ReleaseIdentityPackagingError, match="release commit"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "work",
        )


def test_work_root_must_be_absolute_private_and_new(tmp_path: Path) -> None:
    repository = _repository(tmp_path)
    with pytest.raises(ReleaseIdentityPackagingError, match="must be absolute"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=Path("relative-work"),
        )

    real = tmp_path / "real-work"
    real.mkdir()
    linked = tmp_path / "linked-work"
    linked.symlink_to(real, target_is_directory=True)
    with pytest.raises(ReleaseIdentityPackagingError, match="real directory"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=linked,
        )

    occupied = tmp_path / "occupied-work"
    occupied.mkdir()
    (occupied / RELEASE_IDENTITY_FILENAME).write_text("stale\n", encoding="utf-8")
    with pytest.raises(ReleaseIdentityPackagingError, match="already exists"):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=occupied,
        )


@pytest.mark.parametrize(
    "conflicting_name",
    [
        f"{RELEASE_IDENTITY_BINDING_MODULE}.py",
        f"{RELEASE_IDENTITY_BINDING_MODULE}.pyc",
        f"{RELEASE_IDENTITY_BINDING_MODULE}.cpython-312-x86_64-linux-gnu.so",
        RELEASE_IDENTITY_BINDING_MODULE,
    ],
)
def test_untracked_reserved_binding_module_cannot_shadow_generated_identity(
    tmp_path: Path,
    conflicting_name: str,
) -> None:
    repository = _repository(tmp_path)
    conflict = repository / "backend" / conflicting_name
    if conflicting_name == RELEASE_IDENTITY_BINDING_MODULE:
        conflict.mkdir()
        conflict = conflict / "__init__.py"
    conflict.write_text(
        'RELEASE_IDENTITY_SHA256 = "attacker-controlled"\n',
        encoding="utf-8",
    )

    with pytest.raises(
        ReleaseIdentityPackagingError,
        match="reserved release identity binding module name is occupied",
    ):
        prepare_frozen_release_identity(
            repository_root=repository,
            work_root=tmp_path / "shadowed-work",
        )


def _windows_stat(*, changed_ns: int, birth_ns: int = 101) -> SimpleNamespace:
    return SimpleNamespace(
        st_dev=7,
        st_ino=11,
        st_mode=0o100644,
        st_nlink=1,
        st_size=17,
        st_mtime_ns=37,
        st_ctime_ns=changed_ns,
        st_birthtime_ns=birth_ns,
        st_file_attributes=32,
        st_reparse_tag=0,
    )


def test_windows_birth_time_remains_part_of_file_identity(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(packaging.os, "name", "nt")

    assert packaging.cross_api_file_identity(
        _windows_stat(changed_ns=211, birth_ns=101)
    ) != packaging.cross_api_file_identity(
        _windows_stat(changed_ns=211, birth_ns=103)
    )


def _read_with_windows_stat_views(
    monkeypatch: pytest.MonkeyPatch,
    *,
    descriptor_changed_ns: tuple[int, int],
) -> bytes:
    visible = _windows_stat(changed_ns=101)
    descriptor_stats = iter(
        _windows_stat(changed_ns=value) for value in descriptor_changed_ns
    )
    chunks = iter((b"release metadata\n", b""))
    fake_path = SimpleNamespace(
        is_symlink=lambda: False,
        lstat=lambda: visible,
    )
    monkeypatch.setattr(packaging.os, "name", "nt")
    monkeypatch.setattr(packaging.os, "open", lambda *_args: 41)
    monkeypatch.setattr(packaging.os, "fstat", lambda _descriptor: next(descriptor_stats))
    monkeypatch.setattr(packaging.os, "read", lambda _descriptor, _size: next(chunks))
    monkeypatch.setattr(packaging.os, "close", lambda _descriptor: None)

    return packaging._read_bounded_regular(
        fake_path,
        label="Windows release metadata",
        max_bytes=1024,
    )


def test_windows_bounded_read_accepts_distinct_path_and_fstat_ctime(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    assert _read_with_windows_stat_views(
        monkeypatch,
        descriptor_changed_ns=(211, 211),
    ) == b"release metadata\n"


def test_windows_bounded_read_rejects_descriptor_metadata_mutation(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    with pytest.raises(ReleaseIdentityPackagingError, match="changed while reading"):
        _read_with_windows_stat_views(
            monkeypatch,
            descriptor_changed_ns=(211, 307),
        )
