"""Feature-gated, app-owned Git worktree Beta service."""

from .errors import (
    GitCommandError,
    GitCommandTimeout,
    GitUnavailableError,
    RepositoryValidationError,
    WorktreeActiveError,
    WorktreeConflictError,
    WorktreeDirtyError,
    WorktreeError,
    WorktreeFeatureDisabled,
    WorktreeNotFoundError,
    WorktreeOwnershipError,
    WorktreePathError,
)
from .service import (
    GcReport,
    NoWorktreeReferences,
    ReconcileReport,
    UnconfiguredWorktreeReferenceGuard,
    WorktreeInspection,
    WorktreeRecord,
    WorktreeReferenceGuard,
    WorktreeReferences,
    WorktreeService,
    WorktreeState,
)
from .runtime import (
    WorktreeBinding,
    WorktreeReleaseResult,
    WorktreeRuntime,
    WorktreeRuntimeReferenceGuard,
    worktree_runtime_enabled,
)

__all__ = [
    "GcReport",
    "GitCommandError",
    "GitCommandTimeout",
    "GitUnavailableError",
    "NoWorktreeReferences",
    "ReconcileReport",
    "RepositoryValidationError",
    "WorktreeActiveError",
    "WorktreeBinding",
    "WorktreeConflictError",
    "WorktreeDirtyError",
    "WorktreeError",
    "WorktreeFeatureDisabled",
    "WorktreeInspection",
    "WorktreeNotFoundError",
    "WorktreeOwnershipError",
    "WorktreePathError",
    "WorktreeRecord",
    "WorktreeReleaseResult",
    "WorktreeReferenceGuard",
    "WorktreeReferences",
    "WorktreeService",
    "WorktreeState",
    "WorktreeRuntime",
    "WorktreeRuntimeReferenceGuard",
    "UnconfiguredWorktreeReferenceGuard",
    "worktree_runtime_enabled",
]
